default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  database: smart_workout_development

test:
  <<: *default
  database: smart_workout_test

production:
  <<: *default
  database: <%= ENV['DB_NAME']%>
  username: <%= ENV['DB_USERNAME']%>
  password: <%= ENV['DB_PASSWORD']%>
